### PR TITLE
chore: fix CI pipeline

### PR DESCRIPTION
**Pull request by jedel1043**
## Description

Fixes our CI so that we're testing PRs and pushes to main.

## How was the code tested?

Locally in my Ubuntu Jammy development setup.

## Checklist

- [x] I am the author of these changes, or I have the rights to submit them.
- [x] I have added the relevant changes to the README and/or documentation.
- [x] I have self reviewed my own code.
- [ ] All requested changes and/or review comments have been resolved.

### CODE REVIEW

**Comment by jedel1043** [comment]
Blocked until https://github.com/charmed-hpc/slurmrestd-operator/pull/20 gets merged.

**Comment by NucciTheBoss** [comment]
@jedel1043 I have reviewed your pull request against slurmrestd 🕵️

**Comment by NucciTheBoss** [comment]
Unblocked since I merged the CI pull request against slurmrestd last night. Nice to have the pipelines up and running again!

**Review by NucciTheBoss — APPROVED** [review]
LGTM. Thank you for this work :rocket:

**Pull request merged**
